---
- name: Setup Qpid on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['qpid']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: 'qs',tags: ['apigee-component']  }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-server-self, server_types: ['qs'], tags: ['self']  }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
